builds:
  - main: ./cmd
    id: "gominelang"
    binary: gominelang

release:
  replace_existing_artifacts: true
  make_latest: false
  prerelease: "true"
  mode: append
  name_template: "{{.ProjectName}}-{{.Version}}"
